AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda layer

Resources:

    MyLayer:
        Type: AWS::Serverless::LayerVersion # More info: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesslayerversion
        Properties:
            CompatibleRuntimes:
                - python3.6
                - python3.7
            ContentUri: src/
            Description: A sample lambda layer
            LayerName: my_layer
            RetentionPolicy: Retain

    LatestLayerVersionParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Description: The ARN of the latest layer version
            Name: /Layers/MyLayer/Latest
            Type: String
            Value: !Ref MyLayer
